run:
	nelua main.nelua --cflags=" -I . -L . "
c:
	gcc -x c "shoot_the_red.c" -x none -pipe -fwrapv -fno-strict-aliasing -g -lraylib -lm -o "shoot_the_red"
# the same compilation command as in the C file generated by nelua
